### ISSUE TITLE
Unable to connect to support but Mac App just cycles blank page with home view

### ISSUE THREAD

**Issue by Rickmgoldie-gobrik** [mattermost/mattermost-handbook#1100]
The native app is unusable and has been for a while. I have completely removed it and downloaded a fresh copy of the app. 
I can launch it, set up the server URL and get a brief load of the home page with the channels on the left, but then the screen blanks after less than one second and reappears for 1/10th of a second every 1.5 seconds roughly ad-infinitum.

I can log in with web app in Safari but I would prefer to use the app, so all my credentials are not forgotten every time I clear cache for development needs for instance.

**Comment by justinegeffen** [comment]
Hi @Rickmgoldie-gobrik! I'm sorry you're having a frustrating time with the app and thanks for letting us know. Would you be open to posting about your issue in the [troubleshooting forum](https://forum.mattermost.com/c/trouble-shoot/16)? Another option is to contact our support team at support@mattermost.com.

**Comment by Rickmgoldie-gobrik** [comment]
Fixed in version 5.2.0

**Comment by justinegeffen** [comment]
Fantastic, thanks for letting me know! Can I go ahead and close this issue?

**Comment by justinegeffen** [comment]
Related [forum thread](https://forum.mattermost.com/t/mac-app-unusable-due-to-cyclic-screen-blanking/14188)
