### ISSUE TITLE
Document Joint Development Program

### ISSUE THREAD

**Issue by it33** [mattermost/mattermost-handbook#116]
Write-up a "joint development program" description for how to invite EE customers can elect to participate in EE roadmap and design discussions. 

EE team wants feedback, many customers want to be involved, and we need a more structured way of communicating and participating.

**Comment by justinegeffen** [comment]
@wiersgallak: this may be a good addition to the Product Management Handbook?

**Comment by wiersgallak** [comment]
I've assigned this to myself and will work on this when I have some cycles in the upcoming weeks.
