### ISSUE TITLE
Gif doesn't support 

### ISSUE THREAD

**Issue by Nirajmakwana** [mattermost/mattermost-handbook#1167]
matter most doesn't support Gif can you provide that features because so many users try to send Gif but they cant so try to support Gif and other File types also

**Comment by amyblais** [comment]
Hi @Nirajmakwana, Gif can be enabled via https://docs.mattermost.com/configure/plugins-configuration-settings.html#id8.

**Comment by Nirajmakwana** [comment]
if i send GIf its show like static image not like Gif
