### ISSUE TITLE
Deprecate Hacktoberfest event organizer guide for Mattermost

### ISSUE THREAD

**Issue by azigler** [mattermost/mattermost-handbook#1246]
The `contributors/contributors/guidelines/hacktoberfest-mattermost-organizer-guide.md` page needs to be deprecated ahead of Hacktoberfest 2023:

https://handbook.mattermost.com/contributors/contributors/guidelines/hacktoberfest-mattermost-organizer-guide

@jasonblais confirmed on this Asana task: https://app.asana.com/0/0/1205096986170016/f

@cwarnermm could I tag your help with this issue?

**Comment by cwarnermm** [comment]
Deprecated via https://github.com/mattermost/mattermost-handbook/pull/1247
