### ISSUE TITLE
Handbook logo is a black square

### ISSUE THREAD

**Issue by azigler** [mattermost/mattermost-handbook#1313]
The logo in the top left of the web page is a solid black square. If I alter the CSS color for the background to be white, I can then see an "M" for Mattermost. The logo is showing black text on a black background.

<img width="358" alt="image" src="https://github.com/mattermost/mattermost-handbook/assets/7295363/f2328865-7076-46c4-973c-cd21d4032558">

**Comment by cwarnermm** [comment]
This issue appears to be resolved:
![image](https://github.com/mattermost/mattermost-handbook/assets/74422101/6c5509b0-30ea-4e90-af14-f0610cb81def)
