### ISSUE TITLE
Request for Documentation: FAQ: How to stop receiving notifications for all conversations in handbook repository?

### ISSUE THREAD

**Issue by matterdoc** [mattermost/mattermost-handbook#192]
Mattermost user `jason.blais` from https://community-release.mattermost.com has requested the following be documented:

```
#### How to stop receiving notifications for all conversations in handbook repository?

I've heard a few of you are getting inundated with notifications from handbook - to resolve it, go to https://github.com/mattermost/mattermost-handbook, click the "Watch" icon in top right, then choose your notification preferences.

Generally I'd recommend choosing the `Not Watching` option where you get notified only if you're participating (e.g. submit a pull request), or are @mentioned.
```

See the original post [here](https://community-release.mattermost.com/_redirect/pl/3e93f5hxb3nt3m8ewczhydhjyr).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by cwarnermm** [comment]
Documented by: https://github.com/mattermost/mattermost-handbook/pull/1251

**Comment by jasonblais** [comment]
Thanks Carrie!
