### ISSUE TITLE
Formalize trivia hour as part of the Mattermost workplace program

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-handbook#230]
Proposal for a trivia hour is part of a broader workplace program (see links below). Opening a GitHub issue to formalize the sessions here.

 - GoogleDoc: https://docs.google.com/document/d/1rJGQmsm7VcUng21NO8KjxMf4S1TWbGeFL2hQrbhzRxE
- ISP: https://docs.google.com/document/d/1Po8kChlL9f2O0R6CCxw40VY3c2A4Ij0c1so74rlM050/edit

----

###### Cadence

Two trivia sessions per month with alternating early and late day sessions to cover timezones. 

Need to determine dates/times, as well as who manages the trivia sessions.

###### Logistics

Trivia Teams will be randomized through [Zoom Breakout Rooms](https://support.zoom.us/hc/en-us/articles/206476093-Enabling-breakout-rooms).

Need to determine how to sign up, hosts, and prizes. Some suggestions below:

  - Host

    - Responsible for Trivia questions and hosting the event 
    - Suggestion: Host sign-ups, to allow all staff to participate in trivia events 

  - Prize

    - Mattermost Badge? 
    - MM Swag (can have a select few options to choose from, non-apparel for ease of selection)?

**Comment by justinegeffen** [comment]
@hannaparks, is this something we can resurrect as part of our social activities? :)
