### ISSUE TITLE
No reference to handbook guidelines in handbook PR template

### ISSUE THREAD

**Issue by it33** [mattermost/mattermost-handbook#43]
When creating a new PR for handbook there's no reference to handbook guidelines, only generic PR description, which seems more for code PRs than doc PRs

![image](https://user-images.githubusercontent.com/177788/74668949-1ab27c00-515b-11ea-9f91-018011e8805f.png)

**Comment by jasonblais** [comment]
@it33 Thank you, good catch. I forgot to create a pull request template for this repo. PR submitted to create one: https://github.com/mattermost/mattermost-handbook/pull/44
