### ISSUE TITLE
Request for Documentation: Need guidance on developers going to conferences

### ISSUE THREAD

**Issue by justinegeffen** [mattermost/mattermost-handbook#52]
Moving [this issue](https://github.com/mattermost/docs/issues/2980) from the docs repo to Handbook so it can be addressed. 

"Mattermost user corey from https://community-daily.mattermost.com has requested the following be documented:
Developer Conference Guidelines"

**Comment by justinegeffen** [comment]
Hey, @aspleenic! This looks like something that could be added to [this page](https://handbook.mattermost.com/operations/research-and-development/product/developer-relations) when you next do an update. :)

**Comment by aspleenic** [comment]
Thanks, @justinegeffen - I'll take a look!

**Comment by aspleenic** [comment]
@justinegeffen is this like Code of Conduct for how a dev behaves attending an event? I've just added the guidelines for staffing the booth - is this different from that?

**Comment by justinegeffen** [comment]
Great question, @aspleenic! The original issue is relatively vague but having read your PR I think it's a great start and we can close this issue. :)
