### ISSUE TITLE
A link in localization.md is 404 NotFound

### ISSUE THREAD

**Issue by kaakaa** [mattermost/mattermost-handbook#635]
## Summary

The link for `ICU Message Syntax simplified documentation` pointing to https://formatjs.io/docs/icu-syntax is 404 NotFound.

https://github.com/mattermost/mattermost-handbook/blob/0.2.1/contributors/contributors/localization.md#message-syntax
> If you don't know about the ICU syntax, please familiarize yourself by reading the ICU Message Syntax simplified documentation. What's most important here is to read the section dedicated to how plural terms are managed.

## Notes
`format.js` doesn't seem to have any pages about ICU syntax. https://formatjs.io/docs/core-concepts/icu-syntax/ has a few references to ICU, but they don't seem to be enough. That page has a link to [Formatting Messages \- ICU Documentation](https://unicode-org.github.io/icu/userguide/format_parse/messages/) and it seems to be enough. However, I don't know if replacing old link with [Formatting Messages](https://unicode-org.github.io/icu/userguide/format_parse/messages/) is better because I don't know the page content of the previous link.

**Comment by justinegeffen** [comment]
Thanks for picking this up, @kaakaa! I've opened a PR for the change, with an updated link as well as an additional link to cover all the bases. Let me know if you have any feedback! :)

**Comment by kaakaa** [comment]
Thanks @justinegeffen ! Your changes looks good to me 👍 
Just one point. Are `2. 2. ` and `3. 3.` in [these line](https://github.com/mattermost/mattermost-handbook/pull/637/files#diff-cc52dcbdf788bceccaaff658edc7317783ee1d1b4299e1e34b5e359cfe780519R85-R86) right?

**Comment by kaakaa** [comment]
fixed by #637.

Thanks @justinegeffen !
