### ISSUE TITLE
PNG logo links are broken

### ISSUE THREAD

**Issue by nathanaelhoun** [mattermost/mattermost-handbook#648]
The [PNG logo download links on the visual guidelines page](https://handbook.mattermost.com/operations/operations/company-processes/publishing/publishing-guidelines/brand-and-visual-design-guidelines#png-files) are broken.

The previous ones (before https://github.com/mattermost/mattermost-handbook/pull/643) are fine.

**Comment by justinegeffen** [comment]
Hi @nathanaelhoun! Thanks so much for letting us know. I've taken a look at the links and they appear to be working - could you let me know the error you experienced so I can try replicate and resolve it? :)

**Comment by nathanaelhoun** [comment]
Hey @justinegeffen ! It's works now, seems to be resolved by https://github.com/mattermost/mattermost-handbook/pull/683. Thanks!

**Comment by justinegeffen** [comment]
Yay, awesome. Thanks for confirming. :)
