### ISSUE TITLE
Is there a license for this handbook?

### ISSUE THREAD

**Issue by essential-randomness** [mattermost/mattermost-handbook#704]
Hello! I'm in the process of establishing practices and guidelines for my own open source project. I stumbled upon your handbook, and I've found many sections I'd like to use as a base for my own practices (like the mindsets one, for example). 

Are there specific guidelines/policies on reusing or expanding on some of your writing?

Thank you!

**Comment by justinegeffen** [comment]
Hi @essential-randomness.

Great question. I'm looping @jasonblais into this so we can discuss your question in more detail. :)

**Comment by jasonblais** [comment]
@justinegeffen could we add the same license info from the top of the docs README file? https://github.com/mattermost/docs#mattermost-documentation

Basically I'm thinking we use the [Creative Commons License](https://creativecommons.org/licenses/by-nc-sa/3.0/) for the handbook, as we use for the docs. @essential-randomness that should allow you then to build upon the handbook content we have today.

**Comment by justinegeffen** [comment]
Thanks @jasonblais! I've opened a PR for that.

@essential-randomness, it's really awesome that you're setting up a Handbook for your organization. :) If you have any feedback for us on our Handbook or any content please don't hesitate to open an issue or PR. We appreciate feedback and suggestions for improvement. :)

**Comment by essential-randomness** [comment]
Thank you so much everyone for making this happen!

I'm just at the beginning of the journey, and there's so little guidance on how to successfully run something like this. It's great to be able to take from your handbook and experience.

I'll make sure to let you know my impressions as I dive deeper.

**Comment by SMR39** [comment]
@jasonblais  I wanted to know if a commercial org can also build on top this handbook for internal team purposes. 
we are also happy to make it open.

**Comment by jasonblais** [comment]
@SMR39 you're free to use it under the Creative Common License 3.0 terms: https://creativecommons.org/licenses/by-nc-sa/3.0/
