### ISSUE TITLE
PNG links are broken on multiple help pages

### ISSUE THREAD

**Issue by engineereng** [mattermost/mattermost-handbook#714]
The autocomplete PNG on the [Executing Commands](https://community.mattermost.com/help/commands) page is broken, as are the PNGs on the [Messaging Basics](https://community.mattermost.com/help/messaging) and [Formatting](https://community.mattermost.com/help/formatting) pages.

The full list of broken PNGs is:
- reply arrow (Messaging Basics)
- markdown
- autocomplete (Executing Commands)
- go syntax-highlighting (Formatting; there are four files of this name)

**Comment by justinegeffen** [comment]
Thank you for raising this! The documents you've mentioned are currently being updated by @cwarnermm and these issues will be resolved. :)

**Comment by engineereng** [comment]
Great to hear! Thanks for the update.
