### ISSUE TITLE
Request for documentation: Document process for GDPR requests

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-handbook#775]
Include a note that all GDPR requests should be sent to privacy@mattermost.com

**Comment by justinegeffen** [comment]
@jasonblais, this seems like an easy issue to resolve. Do you have a place in mind for the content? :)

**Comment by jasonblais** [comment]
I'd say under Privacy: https://handbook.mattermost.com/operations/security/privacy

**Comment by cwarnermm** [comment]
Documented by: https://github.com/mattermost/mattermost-handbook/pull/1252
