### ISSUE TITLE
Incomplete sentence

### ISSUE THREAD

**Issue by HilaryClarke** [mattermost/mattermost-handbook#86]
The Best Practices sentence is incomplete, "In our self-awareness means "
Submitting an issue because I don't know how to resolve it.

**Comment by justinegeffen** [comment]
Thanks, @HilaryClarke! I've located the [best practices section](https://handbook.mattermost.com/company/about-mattermost/list-of-terms#best-practices). Would you be open to letting me know whether to remove that sentence fragment or, if not, what the ending should be? :)

**Comment by HilaryClarke** [comment]
I don't, unfortunately. I was curious how the sentence ended myself. I don't know who wrote this or what the intended meaning is.

**Comment by justinegeffen** [comment]
No worries at all. I've removed it and it's been merged. 

Based on the sentence about iteration, I suspect it may have been the beginning of a sentence detailing how self-awareness is counter-cultural to "best practices" followed by a similar detail for earn trust. 

I'll open a separate issue for this as it requires more discussion.
