### ISSUE TITLE
Update link for Hacktoberfest 2021

### ISSUE THREAD

**Issue by noviicee** [mattermost/mattermost-handbook#860]
The `Mattermost Hacktoberfest Tips` link in the Resources leads to the documentation of Hacktoberfest 2018. It should direct to the Tips for Hacktoberfest 2021 now.

![image](https://user-images.githubusercontent.com/72334601/135963420-069c97be-063d-4841-81b0-7f5c0721334c.png)

**Comment by noviicee** [comment]
May I fix this..?

**Comment by jasonblais** [comment]
Thanks @noviicee for your help :)

**Comment by noviicee** [comment]
> Thanks @noviicee for your help :)

Glad to contribute 😄
