### ISSUE TITLE
Required reviewers

### ISSUE THREAD

**Issue by it33** [mattermost/mattermost-handbook#923]
@justinegeffen is there a way to have me as required review on this page: https://github.com/mattermost/mattermost-handbook/blob/0.2.1/operations/operations/company-processes/company-agreements.md

E-sign is something super important to the company and for security and consistency, I'd like to have this in place. There's a few places where we're a bit out-of-sync.

**Comment by justinegeffen** [comment]
I completely understand, and agree. From what I have read [here](https://www.fullstory.com/blog/taming-github-codeowners-with-bots/) I believe you can be added as a code-owner for a specific directory or file which means you'd be auto-added when that file is edited. I've not yet delved into it but will do so post 6.2. 

In the interim, I'll ensure that you're added as a reviewer whenever this page is updated.

**Comment by justinegeffen** [comment]
This has been implemented for the mentioned folder and two others.
