### ISSUE TITLE
Community Chat link is broken

### ISSUE THREAD

**Issue by jsoref** [mattermost/mattermost-handbook#935]
## Steps
1. Visit https://mattermost.com/contribute/
2. Click `Community Chat`
  ![image](https://user-images.githubusercontent.com/2119212/147909651-5a719a6f-5574-4a3b-95b8-d8e2065bcf03.png)

## Actual results

https://community-release.mattermost.com/?redirect_to=%2Fcore%2Fchannels%2Fpeer-to-peer-help
503 Service Temporarily Unavailable
nginx

**Comment by jasonblais** [comment]
Thank you @jsoref! We'll get that fixed 

In the meantime, you can access our community chat at: https://community.mattermost.com/?redirect_to=%2Fcore%2Fchannels%2Fpeer-to-peer-help
