### ISSUE TITLE
Make the process of creating a new page in handbook more clear

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-handbook#96]
Existing process:

Make it more clear that the following should be part of the PR that adds a new page:
- name the file so it has an extension ".md". E.g. "hr-cadence.md". This means the file is Markdown formatted.
- include a title for the page
- add it to the left-hand side navigation https://handbook.mattermost.com/company/how-to-guides-for-staff/how-to-update-handbook#how-do-i-update-the-left-hand-navigation

**Comment by cwarnermm** [comment]
Addressed via https://github.com/mattermost/mattermost-handbook/pull/1254

**Comment by jasonblais** [comment]
Closed by https://github.com/mattermost/mattermost-handbook/pull/1254
